This notebook is to run word frequency analyses on my data, which I obtained by pinging the Congress.gov API, detailed in my data exploration notebook.

In [1]:
import spacy
from collections import Counter
import pandas as pd

# Load spaCy's English model
nlp = spacy.load("en_core_web_sm")

In [2]:
df_house119 = pd.read_csv('house119_enviromeetings.csv')

In [3]:
df_house118 = pd.read_csv('house118_enviromeetings.csv')

In [4]:
df_house117 = pd.read_csv('house117_enviromeetings.csv')

In [5]:
df_house116 = pd.read_csv('house116_enviromeetings.csv')

In [6]:
df_house115 = pd.read_csv('house115_enviromeetings.csv')

In [7]:
df_house114 = pd.read_csv('house114_enviromeetings.csv')

In [8]:
df_senate119 = pd.read_csv('senate119_enviromeetings.csv')

In [9]:
df_senate118 = pd.read_csv('senate118_enviromeetings.csv')

In [10]:
df_senate117 = pd.read_csv('senate117_enviromeetings.csv')

In [11]:
df_senate116 = pd.read_csv('senate116_enviromeetings.csv')

In [12]:
#df_house110, df_house111, df_house112, df_house113, 

senate_dataframes = [df_senate116, df_senate117, df_senate118, df_senate119]
house_dataframes = [df_house114, df_house115, df_house116, df_house117, df_house118, df_house119]

Make lists of all of the titles to run my frequency analysis on

1 for House meetings in R controlled congresses
1 for House meetings in D controlled congresses
1 for Senate meetings in R controlled congresses
1 for Senate meetings in D controlled congresses

In [13]:
# empty lists to fill for all the titles of meetings unde R controlled Congresses and under D controlled Congresses  

meetingnames_R_house_controlled = []
meetingnames_D_house_controlled = []

meetingnames_R_senate_controlled = []
meetingnames_D_senate_controlled = []

Now fill them, by running through each Congress and appending to the appropriate list

In [14]:
## for House 

house_D_controlled = [117, 116, 111, 110] # lists of the Congresses congrolled by Democrats and Republicans
house_R_controlled = [119, 118, 115, 114, 113, 112]

for df in house_dataframes:

    congress = df['congress'].iloc[0]

    if congress in house_D_controlled: # if the Congress number is D controlled 
        for title in df['title']: # then run through each item in the list
            print(title)
            meetingnames_D_house_controlled.append(title)

    elif congress in house_R_controlled: # if the Congress number is r controlled 
        for title in df['title']:
            meetingnames_R_house_controlled.append(title)

#print it out
print('House:')
print(len(meetingnames_D_house_controlled))
print(len(meetingnames_R_house_controlled))

Ocean Climate Action: Solutions to the Climate Crisis. Legislative hearing on H.R. 8632, the Ocean-Based Climate Solutions Act, and H.R. 3548, H.R. 3919, H.R. 4093, H.R. 5390, H.R.5589, H.R.7387, H.R. 8253, H.R.8627
Environmental Justice for Coastal Communities: Examining Inequities in Federal Grantmaking
“Generating Equity: Improving Clean Energy Access and Affordability” - Virtual Hearing
Markup of HR 244, HR 733, HR 970, HR 1248, HR 1964, HR 3225, HR 3651, HR 4135, HR 4139, HR 4840, HR 5153, HR 5458, HR 5459, HR 5472, HR 5598, HR 5852, HR 7098, HR 7099, S. 212
H.R. 5986,  To restore, reaffirm, and reconcile environmental justice and civil rights, provide for the establishment of the Interagency Working Group on Environmental Justice Compliance and Enforcement, and for other purposes. “Environmental Justice for All Act”.
Legislative Hearing on H.R. 7565 and H.R. 8255
"Puerto Rico’s Options for a Non-Territory Status and What Should Happen After November’s Plebiscite"
"Health Care Lifeline: The Affordable Care Act and the COVID-19 Pandemic" (Virtual Hearing)
Examining the Barriers and Solutions to Diversity, Equity, and Inclusion at the Department of the Interior
"Examining the Bureau of Indian Education's School Reopening Guidance During the COVID-19 Pandemic"
“A Public Health Crisis: The Gun Violence Epidemic in America.”
“Protecting Scientific Integrity in the COVID-19 Response”
FC Markup on Multiple Bills
"Pathway to a Vaccine: Efforts to Develop a Safe, Effective and Accessible COVID-19 Vaccine"(Virtual Hearing)
The Transformation of the Puerto Rico Electric Power Authority (PREPA)
Legislative Hearing on H.R. 4345, H.R. 4840, H.R. 5458, H.R. 5459, H.R. 5472, H.R. 5852, H.R. 7098, & H.R. 7489
“Energy Infrastructure and Environmental Justice: Lessons for a Sustainable Future.”
"Oversight of DOE During the COVID-19 Pandemic" (Hybrid Hearing)
“Health Care Inequality: Confronting Racial and Ethnic Disparities in COVID-19 and the Health Care System”
(Virtual Hearing)
“Reviving our Economy: COVID-19’s Impact on the Energy Sector”
(Virtual Hearing)
PROMESA Implementation during the Coronavirus Pandemic
“Pollution and Pandemics: COVID-19’s Disproportionate Impact on Environmental Justice Communities”

(Virtual Hearing)
“Oil and Gas Development in California: The Need to Protect Public Health and the Environment”
Legislation to Reauthorize the Chemical Facility Anti-Terrorism Standards (CFATS) Program and Phase Down the Production and Consumption of Hydrofluorocarbons (HFCs)
"The Irreparable Environmental and Cultural Impacts of the Proposed Resolution Copper Mining Operation”
Markup of: HR 139, “Springfield Race Riot National Historic Monument Act”; HR 1162, “Water Recycling Investment and Improvement Act”; HR 2473, “Securing Access for the central Valley and Enhancing (SAVE) Water Resources Act”; HR 3094, To designate the National Pulse Memorial located at 1912 South Orange Avenue, Orlando, Florida, 32806, and for other purposes; HR 3250, “Julius Rosenwald and the Rosenwald Schools Act of 2019”; HR 3349,“Republic of Texas Legation Memorial Act”; HR 3723, “Desalination Development Act”; HR 4153, “Health Care Access for Urban Native Veterans Act”; HR 4891, “Western Water Security Act of 2019”; HR 5068,“Women Who Worked on the Home Front World War II Memorial Act”; and HR 5126, "Direct Enhancement of Snapper Conservation and the Economy through Novel Devices Act of 2019” or the “DESCEND Act of 2019.”
"Examining the Policies and Priorities of the Bureau of Ocean Energy Management, the Bureau of Safety and Environmental Enforcement, the U.S. Geological Survey, the Bureau of Land Management, and the Office of Surface Mining Reclamation and Enforcement”
Examining the Spending Priorities and Missions of the U.S. Forest Service and the Bureau of Land Management
"Strengthening Communications Networks to Help Americans in Crisis"
Examining the Department of the Interior’s Spending Priorities and the President’s Fiscal Year 2021 Budget Proposal
The Fiscal Year 2021 HHS Budget and Oversight of the Coronavirus Outbreak
In the Dark: Lack of Transparency in the Live Event Ticketing Industry
"Destroying Sacred Sites and Erasing Tribal Culture: The Trump Administration’s Construction of the Border Wall"
Legislative hearing on HR 5435, “American Public Lands and Waters Climate Solution Act of 2019,” and  HR 5859, “Trillion Trees Act.”
"Protecting Women's Access to Reproductive Health Care"
Vaping in America: E-Cigarette Manufacturers’ Impact on Public Health
H.R. 5598, "Boundary Waters Wilderness Protection and Pollution Prevention Act"
Markup of: HR 1049,  “National Heritage Area Act of 2019”; HR 1240, “Young Fishermen's Development Act of 2019”; HR 2748,“Safeguarding America's Future and Environment Act”; HR 2795, “Wildlife Corridors Conservation Act of 2019”; H.R. 2956, To provide for the establishment of the WEstern Riverside Country Wildlife Refuge; HR 3399, To amend the Nutria Eradication and Control Act of 2003 to include California in the program, and for other purposes; HR 4348, “Protect America's Wildlife and Fish In Need of Conservation Act of 2019”; HR 4679, “Climate-Ready Fisheries Act of 2019”; and HR 5179, “Tribal Wildlife Corridors Act of 2019.”
Legislative Hearing on H.R. 4891, H.R. 5316, and H.R. 5347
"The Importance of Public Disclosure Requirements for Protecting Human Health, the Climate, and the Environment"
"Lifting Voices: Legislation to Promote Media Marketplace Diversity"
Legislative Hearing on H.R. 1834, H.R. 2236, H.R. 4679, H.R. 4723, H.R. 5126, and H.R. 5548
"Legislation to Improve Americans' Health Care Coverage and Outcomes"
Securing the U.S. Drug Supply Chain: Oversight of FDA’s Foreign Inspection Program
"Reviewing the Broken Promises Report: Examining the Chronic Federal Funding Shortfalls in Indian Country"
H.R. 3851, the "Travel Promotion, Enhancement, and Modernization Act of 2019" and H.R. 4779, to extend the US SAFEWEB Act of 2006, and for other purposes. and
Legislative Hearing on H.R. 4248, "Surface Mining Control and Reclamation Act Amendments of 2019"
Roads to Ruin: Examining the Impacts of Removing National Forest Roadless Protections
Sexual Harassment at the Department of the Interior
PROMESA: Discussion Draft – Day Two
Legislative hearing on H.R. 139, H.R. 486, H.R. 3250, H.R. 3824, and H.R. 4139
Sabotage: The Trump Administration’s Attack on Health Care
No More Standoffs: Protecting Federal Employees and Ending the Culture of Anti-Government Attacks and Abuse
PROMESA: Discussion Draft – Day One
“The Case for Climate Optimism: Realistic Pathways to Achieving Net Zero Emissions.”
Legislative Hearing on H.R. 2420
Legislative Hearing: H.R. 3160 and S. 46
Wildlife Legislative Hearing on H.R. 925, H.R. 1747, H.R. 2748, H.R. 2854, H.R. 2956, H.R. 2918, H.R. 3399, H.R. 4340, H.R. 4341 and H.R. 4348
Legislative Hearing on H.R. 1312, S. 216, H.R. 3846, H.R. 4153.
Legislative Hearing on H.R. 496, H.R. 2485, H.R. 2640, H.R. 4026, and H.R. 4299
Protecting Unaccompanied Children: The Ongoing Impacts of the Trump Administration’s Cruel Policies
BLM Disorganization: Examining the Proposed Reorganization and Relocation of the Bureau of Land Management Headquarters to Grand Junction, Colorado
Member Day Hearing
Legislative Hearing on H.R. 335, H.R. 729, H.R. 2185, H.R. 3115, H.R. 3237, H.R. 3510, H.R. 3541, H.R. 3596, H.R. 3723
“Increasing Renewable Energy on Public Lands”
When Science Gets Trumped: Scientific Integrity at the Department of the Interior
H.R. 934, “Health Benefits for Miners Act of 2019”

H.R. 935, “Miners Pension Protection Act”
The Status of the Reclamation Fund and the Bureau of Reclamation’s Future Infrastructure Funding Needs
H.R. 3375, H.R. 2211, H.R. 3172, H.R. 3170, H.R. 1618, H.R. 806, H.R. 2647, H.R. 1315, H.R. 2665, H.R. 2044, H.R. 359, H.R. 360, H.R. 362, H.R. 370, H.R. 2088, H.R. 2041, H.R. 2119, H.R. 2781, H.R. 728, H.R. 1058, H.R. 2507, H.R. 776, H.R. 2035, H.R. 2296, and H.R. 2328
Oversight of Federal Efforts to Combat the Spread of Illicit Fentanyl
Legislative Hearing on H.R. 401, H.R. 1492, H.R. 1572, and H.R. 2819
"Our Wireless Future: Building A Comprehensive Approach to Spectrum Policy"
"Oil and Gas Development: Impacts of Business-as-Usual on the Climate and Public Health"
Legislative Hearing: H.R. 3482
H.R. 2414, H.R. 2031, H.R. 895, H.R. 396.
Six Bills to Protect Consumers from Dangerous Products
"Tribal Infrastructure: Roads, Bridges, and Buildings"
Legislative hearing on H.R. 252, H.R. 1475, H.R. 2199, H.R. 2215, H.R. 2250, H.R. 2546, and H.R. 2642.
H.R. 3432, the "Safer Pipelines Act of 2019"
Legislative Hearing on H.R. 644, H.R. 2459, and H.R. 3292
Chronic Wasting Disease: The Threats to Wildlife, Public Lands, Hunting, and Health
“Strengthening Health Care in the U.S. Territories for Today and Into the Future”
"Legislative Solutions to Make Our Nation's Pipelines Safer."
"Oversight of FERC: Ensuring Its Actions Benefit Consumers and the Environment"
"Building a 21st Century American Offshore Wind Workforce"
Legislative Hearing on: H.R. 1373 and H.R. 2181.
Legislative hearing on: H.R. 182, H.R. 307, H.R. 473, H.R. 1088, H.R. 1130, H.R. 1179, H.R. 1248, H.R. 1472, H.R. 1487, H.R. 1727, H.R. 2369, H.R. 2427, H.R. 2490, and H.R. 2525
Responding to the Global Assessment Report of the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services
Examining the President’s Fiscal Year 2020 Budget Proposal for the National Oceanic and Atmospheric Administration and U.S. Fish and Wildlife Service
Legislative Hearing on H.R. 2532, the Tribal Heritage and Grizzly Bear Protection Act (Rep. Grijalva)
"Oil and Gas Development: Impacts of Water Pollution Above and Below Ground"
Examining the President’s Fiscal Year 2020 Budget Proposal for the U.S. Bureau of Reclamation and U.S. Geological Survey
"The Fiscal Year 2020 DOE Budget"
Wildfire Resilient Communities
“Oversight of the Federal Trade Commission: Strengthening Protections for Americans’ Privacy and Data Security”
"Ban Asbestos Now: Taking Action to Save Lives and Livelihoods"
Markup: H.R. 255 (Rep. Cook), To provide for an exchange of lands with San Bernardino County, California, to enhance management of lands within the San Bernardino National Forest, and for other purposes. (Big Bear Land Exchange Act); H.R. 278 (Rep. Newhouse), To direct the Secretary of the Interior to convey certain facilities, easements, and rights-of-way to the Kennewick Irrigation District, and for other purposes; H.R. 312 (Rep. Keating), To reaffirm the Mashpee Wampanoag Tribe reservation, and for other purposes. (Mashpee Wampanoag Tribe Reservation Reaffirmation Act); H.R. 315 (Rep. LaHood), To amend the Surface Mining Control and Reclamation Act of 1977 to authorize partnerships between States and nongovernmental entities for the purpose of reclaiming and restoring land and water resources adversely affected by coal mining activities before August 3, 1977, and for other purposes. (Community Reclamation Partnerships Act); H.R. 375 (Rep. Cole), To amend the Act of June 18, 1934, to reaffirm the authority of the Secretary of the Interior to take land into trust for Indian Tribes, and for other purposes; H.R. 434 (Rep. Jackson Lee), To designate the Emancipation National Historic Trail, and for other purposes. (Emancipation National Historic Trail Act); H.R. 537 (Rep. Lamborn), To amend the Reclamation Project Act of 1939 to authorize pumped storage hydropower development utilizing multiple Bureau of Reclamation reservoirs. (Bureau of Reclamation Pumped Storage Hydropower Development Act); H.R. 1014 (Rep. González-Colón), To amend the Outer Continental Shelf Lands Act to apply to territories of the United States, to establish offshore wind lease sale requirements, to provide dedicated funding for coral reef conservation, and for other purposes;  H.R. 1146 (Rep. Huffman), To amend Public Law 115-97 (commonly known as the Tax Cuts and Jobs Act) to repeal the Arctic National Wildlife Refuge oil and gas program, and for other purposes.  (Arctic Cultural and Coastal Plain Protection Act); H.R. 1261 (Rep. DelBene), To establish a national program to identify and reduce losses from landslide hazards, to establish a national 3D Elevation Program, and for other purposes. (National Landslide Preparedness Act); H.R. 1568 (Rep. Moulton), To assist in the conservation of the North Atlantic right whale by supporting and providing financial resources for North Atlantic right whale conservation programs and projects of persons with expertise required for the conservation of North Atlantic right whales, and for other purposes.  (SAVE Right Whales Act); H.R. 1809 (Rep. Sablan), To amend the Pittman-Robertson Wildlife Restoration Act and the Dingell-Johnson Sport Fish Restoration Act, to provide parity for United States territories and the District of Columbia, to make technical corrections to such Acts and related laws, and for other purposes; and, H.R. 2156 (Rep. Cartwright), To amend the Surface Mining Control and Reclamation Act of 1977 to provide funds to States and Indian tribes for the purpose of promoting economic revitalization, diversification, and development in economically distressed communities through the reclamation and restoration of land and water resources adversely affected by coal mining carried out before August 3, 1977, and for other purposes. (RECLAIM Act of 2019)
"The Status of the Puerto Rico Oversight, Management, and Economic Stability Act (PROMESA): Lessons Learned Three Years Later"
"The State of Pipeline Safety and Security in America"
The State of Fisheries
Legislative Hearing on: H.R. 642, H.R. 1049, H.R. 1990, and H.R. 2288
No Road Map, No Destination, No Justification: The Implementation and Impacts of the Reorganization of the Department of the Interior
“Public Lands and our Clean Energy Future”
“The Status of the ‘Rebuilding and Privatization of the Puerto Rico Electric Power Authority’, (PREPA)”
Legislative hearing on H.R. 1904 (Rep. Grijalva), To amend the Omnibus Public Land Management Act of 2009 to make the Reclamation Water Settlements Fund permanent. “Indian Water Rights Settlement Extension Act”
“Protecting Coastal Communities from Offshore Drilling”
WOW 101: The State of Western Water Infrastructure and Innovation
Examining the Department of the Interior’s Spending Priorities and the President’s Fiscal Year 2020 Budget Proposal”
"Mismanaging Chemical Risks: EPA's Failure to Protect Workers"
Unmasking the Hidden Crisis of Murdered and Missing Indigenous Women (MMIW): Exploring Solutions to End the Cycle of Violence
“Examining the Policies and Priorities of the Bureau of Land Management, the United States Forest Service, and the Power Marketing Administrations.”
"Wasted Energy: DOE's Inaction on Efficiency Standards and Its Impact on Consumers and the Climate" (rescheduled from 02.12.2019)
“Examining the Policies and Priorities of the Bureau of Ocean Energy Management, the Bureau of Safety and Environmental Enforcement, and the U.S. Geological Survey”
"We'll Always Have Paris: Filling the Leadership Void Caused by Federal Inaction on Climate Change"
Legislative hearing on H.R. 560, To amend section 6 of the Joint Resolution entitled "A Joint Resolution to approve the Covenant To Establish a Commonwealth of the Northern Mariana Islands in Political Union with the United States of America, and for other purposes". “Northern Mariana Islands Residents Relief Act.”
Climate Change and Public Lands: Examining Impacts and Considering Adaptation Opportunities.
“Inclusion in Tech: How Diversity Benefits All Americans”
The Impacts of Climate Change on Tribal Communities
"Climate Change: The Impacts and the Need to Act"
Full Committee organizational meeting to consider and adopt the Rules of the Committee on Natural Resources for the 116th Congress.
“Improving Access to Care: Legislation to Reauthorize Key Public Health Programs”
“Improving Safety and Transparency in America’s Food and Drugs”
Safeguarding Pharmaceutical Supply Chains in a Global Economy
"Combating an Epidemic: Legislation to Help Patients with Substance Use Disorders"
Sounding the Alarm: The Public Health Threats of E-Cigarettes
"Interior's Royalty Cuts: Thoughtful Policy or Industry Givewaway?"
"Trump Administration Broken Promises on Renewable Energy"
Unanswered Questions About the US Park Police's June 1 Attack on Peaceful Protesters at Lafayette Square
Legislative Hearing on H.R. 958, H.R. 6237, H.R. 6535, H.R. 7119
"Native Youth Perspectives on Mental Health and Healing"
The U.S. Park Police Attack on Peaceful Protesters at Lafayette Square Park
Legislative Hearing on H.R. 4059, H.R. 4495, H.R. 4888, and H.R. 5153
Oversight of NOAA’s Report on Illegal, Unreported, and Unregulated Fishing
"Repurposing the C-Band to Benefit All Americans"
"Reauthorizing Brand USA and the U.S. SAFE WEB Act"
Pending Legislation before the Subcommittee (15 bills)
"Protecting and Securing Chemical Facilities from Terrorist Attacks"
Legislative Hearing on H.R. 733, H.R. 1031, H.R. 1803, and H.R. 2961.
"Summer Driving Dangers: Exploring  Ways to Protect Drivers and their Families"
Legislative Hearing on H.R. 417, H.R. 1023, H.R. 1218, H.R. 1240, H.R. 1314, H.R. 1979, H.R. 2189, H.R. 2405, and H.R. 2406
"Clean Energy Infrastructure and the Workforce to Build It" on H.R. 1315, the "Blue Collar to Green Collar Jobs Development Act of 2019"
“Enhancing Vehicle Technology to Prevent Drunk Driving”
"Protecting Consumer Privacy in the Era of Big Data"
Strengthening Our Health Care System: Legislation to Reverse ACA Sabotage and Ensure Pre-Existing Conditions Protections
“Texas v. U.S.:  The Republican Lawsuit and Its Impacts on Americans with Pre-Existing Conditions”
"Time for Action:  Addressing the Environmental and Economic Effects of Climate Change"
Legislative Hearing on H.R. 4957
"Reviewing the Trump Administration's Approach to the Missing and Murdered Indigenous Women (MMIW) Crisis"
"Investing in America’s Energy Infrastructure: Improving Energy Efficiency and Creating a Diverse Workforce"
Legislative Hearing on H.R. 1964
Federal and State Efforts to Restore the Salton Sea
Police Cameras at the Department of the Interior: Inconsistencies, Failures, and Consequences
"There's Something in the Water: Reforming Our Nation's Drinking Water Standards"
(Virtual Hearing)
Legislative hearing on H.R. 970, H.R. 4135, & H.R. 7550
Legislative Hearing on H.R. 1776, H.R. 2264, H.R. 2492, H.R. 2871, H.R. 3937, H.R. 6761
Legislative Hearing on: H.R. 244, H.R. 1267, H.R. 2611, H.R. 3682, H.R. 5040, H.R. 7045, and H.R. 7099.
Examining Opportunities to Improve Prevention and Response of Sexual Assault and Sexual Harassment at the National Oceanic and Atmospheric Administration
Legislative Hearing on H.R. 3651, H.R. 3681, H.R. 4236, and H.R. 4512.
Markup of: H.R. 644, “Navajo Utah Water Rights Settlement Act of 2019,” H.R. 1904, “Indian Water Rights Settlement Extension Act,” H.R. 4444, “Western Area Power Administration Transparency Act,” H.R. 5316, “Move Water Now Act,” H.R. 5347 “Disadvantaged Community Drinking Water Assistance Act,” S. 832 (Sen. Merkley), A bill to nullify the Supplemental Treaty Between the United States of America and the Confederated Tribes and Bands of Indians of Middle Oregon, concluded on November 15, 1865, and a
Committee resolution authorizing issuance of subpoenas related to mismanagement, waste, fraud, abuse, and wrongful conduct in relation to functions within the jurisdiction of the Committee on Natural Resources.
Policy Priorities for the Administration’s FY 2021 Budget for the Insular Areas
Committee resolution authorizing issuance of subpoenas related to mismanagement, waste, fraud, abuse, and wrongful conduct in relation to functions within the jurisdiction of the Committee on Natural Resources.
“Promoting American Innovation and Jobs: Legislation to Phase Down the Use of Hydrofluorocarbons”

In [15]:
# for Senate

senate_D_controlled = [118, 117, 113, 112, 111, 110] # lists of the Congresses congrolled by Democrats and Republicans
senate_R_controlled = [119, 116, 115, 114]

for df in senate_dataframes:

    congress = df['congress'].iloc[0]

    if congress in senate_D_controlled: # if the Congress number is D controlled 
        for title in df['title']: # then run through each item in the list
            meetingnames_D_senate_controlled.append(title)

    elif congress in senate_R_controlled: # if the Congress number is r controlled 
        for title in df['title']:
            meetingnames_R_senate_controlled.append(title)

# print it out

print('Senate:')
print(len(meetingnames_D_senate_controlled))
print(len(meetingnames_R_senate_controlled))

Senate:
183
163

Combine all items in list in a format spacy likes

In [16]:
meetingnames_R_house_controlled_forspacy = " ".join(meetingnames_R_house_controlled)

In [17]:
meetingnames_D_house_controlled_forspacy = " ".join(meetingnames_D_house_controlled)

In [18]:
meetingnames_R_senate_controlled_forspacy = " ".join(meetingnames_R_senate_controlled)

In [19]:
meetingnames_D_senate_controlled_forspacy = " ".join(meetingnames_D_senate_controlled)

Analyze the Rs and Ds

Define phrases to exclude

In [ ]:
custom_exclude = {
    # process words
    'an oversight hearing', 'a discussion draft', 'oversight field hearing',  # i am keeping just 'oversight' 
    'leg hrg', 'tuesday', 'wednesday', 'thursday', 'oversight hearing', 'hearings', 'a hearing',
    'longworth house office building', 'statements', 'business meeting', 'september', 'opening', 'november', 'certain documents', '_', 'the 1324 longworth house office building',
    '\'" legislative hearing', 'energy and commerce committee vote', 'the establishment', 'full committee markup', 'the development',  'the nominations', 'the nomination', 'inquiry',
    'the subcommittee', 'subcommittee markup', 'this notice', 'other purposes', 'discussion', 'legislative hearing', 'the nature',
    '10:00 a.m.', '12:00 p.m.', '5:00 p.m.', '4:00 p.m.',
    'multiple bills',
    'h.r.', '•\th.r.', '• h.r.', '”\r\n•\th.r.', 'hearings', '”\r\n• h.r.', '•h.r.', '” h.r.', 'hr', 
    
    # bill words
    'that act', 'section', 'an original bill', 'the amendment', 'amendments', 'legislation', 'a markup beginning', 'the conveyance', 'fiscal year', 'the implementation', 'legislative proposals',
    's.', 'the status', 'title', 'a bill', 'discussion draft', "the president's proposed budget request", 'markup', 'a substitute', 'the following bills', 'the amendments', 'amendment', '\" legislative hearing'

    # themed words but for non target topics (note that some of these committees are also health related)
    'agriculture', 'health care costs', 'covid-19', 'the covid-19 pandemic', 'patients', 'the opioid crisis', 'biomedicine'

    'way' # because I want to include "rights of way" and "right of way" as a complete phrase

    # broad actors
    'the secretary', 'deputy secretary'
    'secretary',
    'the committee',
    'the house',
    'the senate',
    'house',
    'senate'

}

In [21]:
custom_include = {

    # CLIMATE CHANGE

    'climate change',
    'climate crisis',
    'climate emergency',
    'climate',
    'reliability',

    #pollution

    'greenhouse gas', 'ghg',
    'methane', 'carbon dioxide', 'co2',
    'particulate matter', 'pfas', 'forever chemicals', 'superfund'

    # ENERGY

    # fossil 
    'fossil,'
    'crude oil',
    'natural gas',
    'coal',
    'petroleum',
    'liquefied natural gas', 
    'fracking',
    'pipelines',
    'refineries',
    'drilling permits',
    'federal lands', 
    'strategic petroleum reserve',
    'hydrocarbons',
    'offshore drilling',
    'leasing',
    'royalties',
    'lng', 'liquefied natural gas',
    
    # renewable 
    'renewable energy',
    'clean energy',
    'wind',
    'solar',
    'nuclear energy'

    # controverical renewbale'
    'hydroelectric',
    'geothermal',
    'hydrogen','green hydrogen', 'clean hydrogen', 
    'biofuels',
    'ethanol', 
    'biomass',
    'carbon capture and sequestration', 'ccs', 'carbon capture and storage', 'carbon capture', 'direct air capture', 'dac', 
    'small modular reactors', 'smrs', 'advanced nuclear',
    'fusion', 'sustainable aviation fuel', 'saf',
    
    # grid & supply chain infrastructure
    'transmission lines', 'interconnection queue',
    'ferc',
    
    # other electricity / grid
    
    'critical minerals', 'supply chain'
    'electric vehicles', 'evs', 'batteries', 'charging stations', 'ev charging',
    'electric', 'electricity',
    'heat pumps', 'rights of way', 'right of way'

    # WEATHER / EXTREME WEATEHR EVENTS

    'extreme weather',
    'wildfires', 'wildfire'
    'drought', 'droughts'
    'sea level rise',
    'flooding', 'floods', 'national flood insurance program', 'nfip'

    # ENERGY MESSAGING

    # progressive / democratic framing
    'climate justice', 'environmental justice', 'existential threat', 'polluters', 'big oil', 'sustainability', 'just transition',
    'clean energy economy', 'decarbonization', 'energy transition', 'targets', 'net-zero', 'net zero', 'zero-emission',
    
    # conservative / republican framing
    'regulatory overreach', 'bureaucrating stringency', 'war on coal', 'green new deal', 
    'unreliable', 'reliable', 'energy tax', 'mandates', 'job', 'jobs', 'china', 'chinese'
    'global competitiveness', 'american energy', 'free market', 'innovation over regulation'
    'all of the above', 'dominance', 'abundance', 'costs', 'prices', 'emergency', 'independence', 'security', 
    
    # other rules and policies

    'environmental protection agency', 'epa',
    'department of energy', 'doe'
    'regulation', 'deregulation'
    'tax credits', 'subsidies',
    'permitting reform',
    'weatherization',
    'carbon tax', 'carbon pricing', 'cap and trade', 'esg',
    'sec disclosure', 'green bonds', 'production tax credit', 'ptc', 'investment tax credit', 'itc',
    'clean air act', 'clean water act'
    'fish and wildlife service', 'fish & wildlife service',
    'inflation reduction act', 'ira',
    'bipartisan infrastructure law', 'bil'
    'energy bill of 2020', '2020 energy law',
    'historic preservation act', #some of these, as this one, were developed because spacy was cutting off the end of some of these phrases
    'bureau of land management', 'blm' # same with this one, didn't want just 'bureau'

    # international treaties

    'paris agreement', 'paris accord', 'kyoto protocol', 'cop', 'united nations', 'un'

    # GEOGRAPHY 

    # all state names and abbreviations

    'alabama', 'al',
    'alaska', 'ak',
    'arizona', 'az',
    'arkansas', 'ar',
    'california', 'ca',
    'colorado', 'co',
    'connecticut', 'ct',
    'delaware', 'da',
    'district of Columbia', 'dc', 'd.c.',
    'florida', 'fl',
    'georgia', 'ga',
    'hawaii', 'hi',
    'idaho', 'id',
    'illinois', 'il',
    'indiana', 'in',
    'iowa', 'ia',
    'kansas', 'ks',
    'kentucky', 'ky',
    'louisiana', 'la',
    'maine', 'me',
    'maryland', 'md',
    'massachusetts', 'ma',
    'michigan', 'mi',
    'minnesota', 'mn',
    'mississippi', 'ms',
    'missouri', 'mo',
    'montana', 'mt',
    'nebraska', 'ne',
    'nevada', 'nv',
    'new hampshire', 'nh',
    'new jersey', 'nj',
    'new mexico', 'nm',
    'new york', 'ny',
    'north carolina', 'nc',
    'north dakota', 'nd',
    'ohio', 'oh',
    'oklahoma', 'ok',
    'oregon', 'or',
    'pennsylvania', 'pa',
    'rhode island', 'ri',
    'south carolina', 'sc',
    'south dakota', 'sd',
    'tennessee', 'tn',
    'texas', 'tx',
    'utah', 'ut',
    'vermont', 'vt',
    'virginia', 'va',
    'washington', 'wa',
    'west virginia', 'wv',
    'wisconsin', 'wi',
    'wyoming', 'wy',

    # other geographic words 

    'southern', 'south',
    'northern', 'north', 'northeast','northeastern', 
    'midwest',
    'pacific northwest',
    'west', 'western', 
    'coastal',
    'gulf coast', 'permian basin', 'gulf of mexico', 'gulf of america'
    'rust belt',
    'sun belt',
    'bible belt',
    'new england',
    'great lakes',
    'appalachia',
    'rural',
    'urban', 'cities', 'city',
    'suburban', 'suburb',

}

R meetings House

In [22]:
doc = nlp(meetingnames_R_house_controlled_forspacy)

noun_phrases = [chunk.text.lower().strip() for chunk in doc.noun_chunks] # Extract grammatical noun phrases, lowercased and stripped of whitespace
# Add the custom included items
noun_phrases.extend(custom_include)

# Filter out specific phrases manually
exclude = custom_exclude

# Filter in specific phrases

text = meetingnames_R_house_controlled_forspacy.lower()
included = [
    phrase for phrase in custom_include
    if phrase in text
    
]

# add in those phrases with spacy's phrases:
the_rest = [p for p in noun_phrases if p not in exclude]

phrase_counts = Counter(the_rest)

df_top_R_house_phrases = pd.DataFrame(phrase_counts.most_common(150), columns=['Noun Phrase', 'Frequency'])

D meetings House

In [23]:
doc = nlp(meetingnames_D_house_controlled_forspacy)

noun_phrases = [chunk.text.lower().strip() for chunk in doc.noun_chunks] # Extract grammatical noun phrases, lowercased and stripped of whitespace
# Add the custom included items
noun_phrases.extend(custom_include)
# Filter out specific phrases manually
exclude = custom_exclude

# Filter in specific phrases

text = meetingnames_D_house_controlled_forspacy.lower()
included = [
    phrase for phrase in custom_include
    if phrase in text
]

# add in those phrases with spacy's phrases:
the_rest = [p for p in noun_phrases if p not in exclude]

phrase_counts = Counter(the_rest)

df_top_D_house_phrases = pd.DataFrame(phrase_counts.most_common(150), columns=['Noun Phrase', 'Frequency'])

R meetings Senate

In [24]:
doc = nlp(meetingnames_R_senate_controlled_forspacy)

noun_phrases = [chunk.text.lower().strip() for chunk in doc.noun_chunks] # Extract grammatical noun phrases, lowercased and stripped of whitespace
# Add the custom included items
noun_phrases.extend(custom_include)
# Filter out specific phrases manually
exclude = custom_exclude

# Filter in specific phrases

text = meetingnames_R_senate_controlled_forspacy.lower()
included = [
    phrase for phrase in custom_include
    if phrase in text
]

# add in those phrases with spacy's phrases:
the_rest = [p for p in noun_phrases if p not in exclude]

phrase_counts = Counter(the_rest)

df_top_R_senate_phrases = pd.DataFrame(phrase_counts.most_common(150), columns=['Noun Phrase', 'Frequency'])

D meetings Senate

In [25]:
doc = nlp(meetingnames_D_senate_controlled_forspacy)

noun_phrases = [chunk.text.lower().strip() for chunk in doc.noun_chunks] # Extract grammatical noun phrases, lowercased and stripped of whitespace
# Add the custom included items
noun_phrases.extend(custom_include)

# Filter out specific phrases manually
exclude = custom_exclude

# Filter in specific phrases

text = meetingnames_D_senate_controlled_forspacy.lower()
included = [
    phrase for phrase in custom_include
    if phrase in text
]

# add in those phrases with spacy's phrases:
the_rest = [p for p in noun_phrases if p not in exclude]

phrase_counts = Counter(the_rest)

df_top_D_senate_phrases = pd.DataFrame(phrase_counts.most_common(150), columns=['Noun Phrase', 'Frequency'])

Save dataframes

In [26]:
df_top_R_house_phrases.to_csv('top_R_house_phrases.csv')

In [27]:
df_top_D_house_phrases.to_csv('top_D_house_phrases.csv')

In [28]:
df_top_R_senate_phrases.to_csv('top_R_senate_phrases.csv')

In [29]:
df_top_D_senate_phrases.to_csv('top_D_senate_phrases.csv')

In [30]:
df_top_D_senate_phrases.head()

      Noun Phrase  Frequency
0       the state         70
1   the secretary         64
2    the interior         55
3          energy         47
4  the department         27

In [31]:
df_top_D_house_phrases.head()

       Noun Phrase  Frequency
0     the interior         13
1    the secretary         13
2   the department         11
3  representatives         11
4          america          9